CREATE TABLE application_followup (
 id UUID PRIMARY KEY,
 user_id UUID NOT NULL REFERENCES app_user(id),
 application_id UUID NOT NULL REFERENCES job_application(id),
 title VARCHAR(240) NOT NULL,
 due_at TIMESTAMP WITH TIME ZONE NOT NULL,
 completed BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
