import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { mkdtemp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { spawn, spawnSync } from 'node:child_process'
import { resolve } from 'node:path'
import { readdirSync } from 'node:fs'
import { chromium } from 'playwright-core'

const root=resolve(import.meta.dirname,'..')
const javaName=process.platform==='win32'?'java.exe':'java'
const localJdkRoot=process.platform==='win32'&&process.env.USERPROFILE?resolve(process.env.USERPROFILE,'.jdks'):''
const localJdks=localJdkRoot&&existsSync(localJdkRoot)
  ?readdirSync(localJdkRoot,{withFileTypes:true}).filter(entry=>entry.isDirectory()&&entry.name.includes('21'))
    .map(entry=>resolve(localJdkRoot,entry.name,'bin',javaName)).filter(existsSync):[]
const javaCandidates=[process.env.JAVA_HOME&&resolve(process.env.JAVA_HOME,'bin',javaName),...localJdks,'java'].filter(Boolean)
const java=javaCandidates.find(candidate=>{
 const version=spawnSync(candidate,['-version'],{encoding:'utf8',windowsHide:true})
 return /version "21(?:\.|\")/.test(`${version.stdout??''}${version.stderr??''}`)
})
if(!java)throw new Error('Full-stack QA requires Java 21. Set JAVA_HOME to a JDK 21 installation.')
const artifactDirectory=await mkdtemp(resolve(tmpdir(),'careerlens-qa-artifacts-'))
const children=[]
let browser
const api='http://127.0.0.1:18084/api/v1', ui='http://127.0.0.1:41731'
const results=[]
function start(command,args,cwd,extra={}){
 const child=spawn(command,args,{cwd,env:{...process.env,...extra},windowsHide:true,stdio:['ignore','pipe','pipe']})
 let logs=''
 child.stdout.on('data',b=>{logs=(logs+b).slice(-8000)})
 child.stderr.on('data',b=>{logs=(logs+b).slice(-8000)})
 child.on('error',e=>{logs+=e.message})
 children.push({child,logs:()=>logs})
 return child
}
async function ready(url){
 for(let n=0;n<90;n++){try{if((await fetch(url,{signal:AbortSignal.timeout(1500)})).ok)return}catch{}
 await new Promise(r=>setTimeout(r,1000))}
 throw new Error('Service startup timeout: '+url+'\n'+children.map(c=>c.logs()).join('\n'))
}
function pass(name){results.push({name,status:'passed'}); console.log('PASS '+name)}
try{
 try{await fetch(api+'/health',{signal:AbortSignal.timeout(500)});throw new Error('QA port 18084 is occupied')}catch(e){if(e.message==='QA port 18084 is occupied')throw e}
 start(java,['-jar','target/core-api-0.1.0-SNAPSHOT.jar','--spring.profiles.active=local',
 '--server.port=18084','--careerlens.artifacts.directory='+artifactDirectory,'--spring.datasource.url=jdbc:h2:mem:qa;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH',
 '--careerlens.cors-origins='+ui,'--careerlens.ai-worker.base-url=http://127.0.0.1:18001','--careerlens.runner.base-url=http://127.0.0.1:1'],resolve(root,'services/core-api'))
 const py=resolve(root,'services/ai-worker/.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python')
 start(existsSync(py)?py:'python',['-m','uvicorn','app.main:app','--host','127.0.0.1','--port','18001'],resolve(root,'services/ai-worker'),{LLM_MODE:'offline'})
 start(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','41731','--strictPort'],root,{VITE_API_BASE_URL:api})
 await Promise.all([ready(api+'/health'),ready(ui),ready('http://127.0.0.1:18001/internal/v1/health')])
 const executablePath=[process.env.PLAYWRIGHT_BROWSER_PATH,'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Google/Chrome/Application/chrome.exe','/usr/bin/chromium','/usr/bin/google-chrome'].find(p=>p&&existsSync(p))
 browser=await chromium.launch({executablePath,headless:true})
 const page=await browser.newPage({viewport:{width:1440,height:1000}})
 page.setDefaultTimeout(15000)
 page.setDefaultNavigationTimeout(45000)
 const pageErrors=[]
 page.on('pageerror',e=>pageErrors.push(e.message))
 await page.goto(ui,{waitUntil:'domcontentloaded'})
 await page.getByRole('button',{name:'创建新账号'}).click()
 await page.getByLabel('姓名',{exact:true}).fill('验收用户')
 await page.getByRole('textbox',{name:/邮箱/}).fill('qa@example.test')
 await page.getByLabel('密码',{exact:true}).fill('QaPass123!')
 await page.getByRole('button',{name:'注册并进入'}).click()
 await page.waitForURL(ui+'/')
 await page.getByText('先填写求职资料').waitFor()
 pass('注册后空工作区')
 const token=await page.evaluate(()=>sessionStorage.getItem('careerlens-access-token'))
 const request=async(path,method='GET',body)=>{
  const r=await fetch(api+path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined})
  const data=r.status===204?null:await r.json();assert.ok(r.ok,JSON.stringify(data));return data
 }
 assert.equal((await request('/resumes')).length,0)
 assert.equal((await request('/applications')).length,0)
 await page.goto(ui+'/resumes')
 await page.getByRole('button',{name:'创建求职资料',exact:true}).first().click()
 await page.waitForURL('**/resumes/editor')
 await page.getByLabel('姓名',{exact:true}).fill('验收用户')
 await page.getByLabel('求职方向',{exact:true}).fill('Java 开发')
 await page.getByLabel('邮箱',{exact:true}).fill('qa@example.test')
 await page.getByLabel('项目名称',{exact:true}).fill('接口服务')
 await page.getByLabel('三句话概括你的方向、能力和特点').fill('使用 Java Spring Boot 开发接口，使用 MySQL 存储数据。')
 await page.getByText(/草稿已保存 · 修订/).waitFor()
 await page.waitForTimeout(1000)
 await page.reload()
 await page.getByLabel('姓名',{exact:true}).waitFor()
 await page.waitForFunction(()=>document.querySelector('#editor-profile input')?.value==='验收用户')
 pass('简历自动保存与刷新持久化')
 const projectSection=page.locator('.dynamic-section').first()
 await projectSection.getByRole('button',{name:'添加条目',exact:true}).click()
 await page.getByLabel('项目名称',{exact:true}).nth(1).fill('第二个真实项目')
 await projectSection.getByLabel('隐藏条目').nth(1).check()
 assert.equal(await page.locator('.resume-paper').getByText('第二个真实项目',{exact:true}).count(),0)
 await projectSection.getByLabel('隐藏条目').nth(1).uncheck()
 await page.waitForTimeout(1100)
 await page.reload()
 await page.waitForFunction(()=>document.querySelectorAll('.dynamic-section')[0]?.querySelectorAll('article').length===2)
 assert.equal(await page.getByLabel('项目名称',{exact:true}).nth(1).inputValue(),'第二个真实项目')
 pass('多条经历、隐藏规则与刷新持久化')
 await page.getByRole('button',{name:/发布(新版本|投递版本)/}).click()
 await page.getByText(/简历 v\d+ 已发布/).waitFor()
 const resume=(await request('/resumes'))[0]
 await page.getByText(/已发布 v\d+/).waitFor()
 await page.goto(ui+'/resumes')
 await page.getByText(/正式版本 v\d+/).waitFor()
 await page.getByText('草稿自动保存',{exact:true}).waitFor()
 await page.locator('.resume-completion').waitFor()
 await page.getByRole('button',{name:'继续编辑'}).click()
 await page.waitForURL('**/resumes/editor')
 pass('求职资料区分草稿、正式版本与完成度')
 assert.ok(resume.completionRate>0)
 assert.ok((await request('/resumes/'+resume.id+'/versions')).length>=2)
 const versions=await request('/resumes/'+resume.id+'/versions')
 const restored=await request('/resumes/'+resume.id+'/versions/'+versions[0].id+':restore','POST')
 assert.ok(restored.version>versions[0].version)
 const diff=await request('/resumes/'+resume.id+'/versions/'+versions[0].id+'/diff/'+restored.id)
 assert.equal(diff.changes.length,0)
 const copy=await request('/resumes/'+resume.id+':duplicate','POST')
 await request('/resumes/'+copy.resume.id,'DELETE')
 pass('版本发布、恢复、比较、复制与删除')
 const artifact=await request('/resume-versions/'+restored.id+'/artifacts','POST')
 const pdf=await fetch(api+'/artifacts/'+artifact.id+'/file',{headers:{Authorization:'Bearer '+token}})
 assert.equal(pdf.status,200);assert.ok((await pdf.arrayBuffer()).byteLength>1000)
 pass('发布版本PDF产物与下载权限')
 const formData=new FormData()
 formData.append('file',new Blob(['姓名：导入用户 | 求职意向：Java 开发\n邮箱：import@example.test\n教育经历\n2020.09 - 2024.06 | 示例大学 | 软件工程 | 本科\n项目经历 导入项目\n2023.01 - 2023.06 | 后端负责人\n- 使用Java实现接口'],{type:'text/plain'}),'resume.txt')
 const imported=await fetch(api+'/resumes/import',{method:'POST',headers:{Authorization:'Bearer '+token},body:formData})
 assert.equal(imported.status,201)
 const parsed=await imported.json()
 assert.ok(parsed.draft.content.sourceDocument.rawText.includes('Java'))
 assert.equal(parsed.draft.content.importReviewPending,true)
 assert.equal(parsed.draft.content.profile.name,'导入用户')
 assert.equal(parsed.draft.content.profile.email,'import@example.test')
 assert.equal(parsed.draft.content.sections[0].items[0].school,'示例大学')
 assert.equal(parsed.draft.content.sections[0].items[0].major,'软件工程')
 assert.equal(parsed.draft.content.sections[1].items[0].title,'导入项目')
 await page.goto(ui+'/resumes')
 await page.locator('.resume-library-card').filter({hasText:'resume.txt'}).getByRole('button',{name:/继续编辑|完善并发布/}).click()
 await page.waitForURL('**/resumes/editor')
 assert.equal(await page.getByLabel('姓名',{exact:true}).inputValue(),'导入用户')
 assert.equal(await page.getByLabel('学校',{exact:true}).inputValue(),'示例大学')
 assert.equal(await page.getByLabel('项目名称',{exact:true}).inputValue(),'导入项目')
 await page.getByText('查看字段识别依据',{exact:true}).click()
 await page.getByText('姓名：导入用户',{exact:true}).waitFor()
 await page.getByRole('button',{name:'重新识别导入内容',exact:true}).click()
 await page.getByRole('alertdialog').getByRole('button',{name:'确认重新识别',exact:true}).click()
 await page.getByText('重新识别完成',{exact:true}).waitFor()
 assert.equal(await page.getByLabel('项目名称',{exact:true}).inputValue(),'导入项目')
 await page.goto(ui+'/resumes')
 await page.locator('.resume-library-card').first().getByRole('button',{name:/继续编辑|完善并发布/}).click()
 pass('文档导入、AI解析与落库')
 await page.goto(ui+'/applications')
 await page.getByRole('button',{name:'添加岗位',exact:true}).click()
 await page.getByLabel('公司名称').fill('验收公司')
 await page.getByLabel('岗位名称').fill('Java 开发')
 await page.getByRole('dialog').getByRole('button',{name:'添加岗位',exact:true}).click()
 await page.locator('.application-card').waitFor()
 await page.reload(); await page.locator('.application-card').waitFor()
 pass('投递记录持久化')
 await page.getByRole('button',{name:'列表视图',exact:true}).click()
 await page.reload();await page.getByRole('button',{name:'列表视图',exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'列表视图',exact:true}).getAttribute('aria-pressed'),'true')
 pass('投递管理视图偏好自动保存')
 const apps=await request('/applications')
 await request('/applications/'+apps[0].id,'PATCH',{stage:'interview',nextActionSet:false})
 assert.equal((await request('/applications'))[0].stage,'interview')
 pass('看板阶段更新')
 const followup=await request('/applications/'+apps[0].id+'/followups','POST',{title:'跟进反馈',dueAt:new Date(Date.now()+86400000).toISOString()})
 assert.ok((await request('/followups')).some(f=>f.id===followup.id))
 await request('/followups/'+followup.id,'PATCH',{completed:true})
 await request('/applications/'+apps[0].id+'/events','POST',{type:'NOTE',detail:'备注验收'})
 assert.ok((await request('/applications/'+apps[0].id)).events.some(e=>e.detail==='备注验收'))
 pass('跟进待办与时间线')
 const todayDue=new Date();todayDue.setHours(23,59,59,0)
 await request('/applications/'+apps[0].id+'/followups','POST',{title:'逾期事项',dueAt:new Date(Date.now()-86400000).toISOString()})
 await request('/applications/'+apps[0].id+'/followups','POST',{title:'今日事项',dueAt:todayDue.toISOString()})
 await request('/applications/'+apps[0].id+'/followups','POST',{title:'未来事项',dueAt:new Date(Date.now()+3*86400000).toISOString()})
 await page.reload()
 await page.locator('.followup-group--danger').getByText('逾期事项',{exact:true}).waitFor();await page.locator('.followup-group--warning').getByText('今日事项',{exact:true}).waitFor();await page.locator('.followup-group--neutral').getByText('未来事项',{exact:true}).waitFor()
 await page.getByRole('button',{name:'看板视图',exact:true}).click()
 await page.locator('.application-card').first().getByText('更多',{exact:true}).click()
 await page.locator('.application-card').first().getByRole('button',{name:'查看时间线',exact:true}).click()
 await page.getByRole('dialog').getByText('备注验收',{exact:true}).waitFor()
 assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden')
 await page.getByRole('dialog').getByRole('button',{name:'添加备注'}).click()
 await page.getByRole('dialog',{name:/添加备注/}).waitFor()
 await page.keyboard.press('Escape')
 await page.getByRole('dialog',{name:/添加备注/}).waitFor({state:'hidden'})
 await page.getByRole('button',{name:'关闭时间线',exact:true}).waitFor()
 await page.keyboard.press('Escape')
 await page.getByRole('dialog').waitFor({state:'hidden'})
 assert.equal(await page.evaluate(()=>document.body.style.overflow),'')
 pass('跟进按逾期今日未来分组并使用时间线抽屉')
 const offline=await fetch(api+'/platforms/boss/connect',{method:'POST',headers:{Authorization:'Bearer '+token}})
 assert.equal(offline.status,409)
 assert.equal((await request('/platforms')).length,0)
 pass('离线执行器不伪造连接或岗位')
 await page.goto(ui+'/automation')
 await page.getByRole('heading',{name:'当前没有活动任务'}).waitFor()
 assert.equal(await page.locator('.automation-current').count(),1)
 assert.equal(await page.locator('.one-stop-status').count(),0)
 assert.equal(await page.locator('.automation-header-actions').getByRole('button',{name:'启动待执行任务'}).count(),0)
 pass('自动执行单一运行状态与操作入口')
 await page.goto(ui+'/settings')
 await page.getByRole('button',{name:'检查服务连接',exact:true}).click()
 await page.getByText('核心服务：UP',{exact:true}).waitFor()
 assert.equal(await page.getByRole('heading',{name:'BOSS直聘',exact:true}).count(),1)
 pass('设置页兼容不完整平台诊断响应')
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:/招呼语策略/}).click()
 await page.getByRole('heading',{name:'首条招呼语策略'}).waitFor()
 assert.equal(await page.getByRole('heading',{name:'BOSS直聘',exact:true}).isVisible(),false)
 await page.reload()
 await page.getByRole('heading',{name:'首条招呼语策略'}).waitFor()
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:/执行策略/}).click()
 await page.getByRole('heading',{name:'执行约束'}).waitFor()
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:/数据维护/}).click()
 await page.getByRole('heading',{name:'数据',exact:true}).waitFor()
 pass('设置分组导航和刷新保留分类')
 await page.getByRole('button',{name:'打开命令搜索'}).click()
 await page.getByRole('dialog',{name:'命令菜单'}).waitFor()
 assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden')
 await page.keyboard.press('Tab')
 assert.equal(await page.getByRole('dialog',{name:'命令菜单'}).evaluate(node=>node.contains(document.activeElement)),true)
 await page.keyboard.press('Escape')
 await page.getByRole('dialog',{name:'命令菜单'}).waitFor({state:'hidden'})
 assert.equal(await page.evaluate(()=>document.body.style.overflow),'')
 assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'打开命令搜索')
 pass('弹层键盘关闭、焦点限制和背景滚动锁定')
 await page.goto(ui+'/discovery')
 const keywordInput=page.getByLabel('添加岗位关键词',{exact:true})
 await keywordInput.fill('配置持久化测试');await keywordInput.press('Enter')
 const manualCity=page.getByPlaceholder('也可手动输入城市后按 Enter',{exact:true})
 await manualCity.fill('南京');await manualCity.press('Enter')
 await page.getByRole('button',{name:'保存配置',exact:true}).click()
 await page.reload()
 await page.getByText('配置持久化测试',{exact:true}).waitFor()
 await page.getByText('南京',{exact:true}).waitFor()
 pass('职位发现配置按当前BOSS账号持久化')
 await page.getByRole('textbox',{name:'新预设名称'}).fill('Java 实习 · 南京')
 await page.getByRole('button',{name:'保存为预设'}).click()
 await page.getByLabel('选择筛选预设').selectOption({label:'Java 实习 · 南京 · 默认'})
 await keywordInput.fill('临时方向');await keywordInput.press('Enter')
 await page.getByRole('button',{name:'应用',exact:true}).click()
 assert.equal(await page.getByText('临时方向',{exact:true}).count(),0)
 await page.getByRole('button',{name:'复制',exact:true}).click()
 await page.reload()
 await page.getByLabel('选择筛选预设').locator('option').nth(2).waitFor({state:'attached'})
 assert.equal(await page.getByLabel('选择筛选预设').locator('option').count(),3)
 pass('职位发现预设保存、应用、复制与刷新持久化')
 await page.goto(ui+'/')
 await page.getByRole('button',{name:'14 天'}).click()
 assert.equal(await page.getByRole('button',{name:'14 天'}).getAttribute('aria-pressed'),'true')
 assert.equal(await page.getByRole('link',{name:/待审核/}).getAttribute('href'),'/review-queue')
 assert.equal(await page.locator('.dashboard-workflow__step').count(),4)
 pass('工作台趋势切换、指标入口与流程导航')
 for(const width of [1440,390]){
  await page.setViewportSize({width,height:900})
  for(const path of ['/','/resumes','/resumes/editor','/jobs','/matches','/suggestions','/applications','/discovery','/review-queue','/automation','/settings']){
   await page.goto(ui+path,{waitUntil:'domcontentloaded'});await page.waitForTimeout(300)
   if(path==='/'&&process.env.CAREERLENS_QA_SCREENSHOTS){
    const screenshotPath=resolve(artifactDirectory,`dashboard-${width}-light.png`)
    await page.screenshot({path:screenshotPath,fullPage:true});console.log('SCREENSHOT '+screenshotPath)
    await page.getByRole('button',{name:'切换深色模式'}).click()
    await page.waitForTimeout(300)
    const darkWorkflow=await page.locator('.dashboard-workflow > a').first().evaluate(element=>({theme:document.documentElement.dataset.theme,background:getComputedStyle(element).backgroundColor,color:getComputedStyle(element).color}))
    assert.notEqual(darkWorkflow.background,'rgb(255, 255, 255)',JSON.stringify(darkWorkflow))
    const darkPath=resolve(artifactDirectory,`dashboard-${width}-dark.png`)
    await page.screenshot({path:darkPath,fullPage:true});console.log('SCREENSHOT '+darkPath)
    await page.getByRole('button',{name:'切换浅色模式'}).click()
   }
   assert.ok(!page.url().includes('/login'),'Route redirected unexpectedly')
   const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}))
   if(size.scroll>size.width+2){
    const overflow=await page.evaluate(()=>[...document.querySelectorAll('*')].map(element=>{const rect=element.getBoundingClientRect();return{tag:element.tagName,className:element.className?.toString?.()??'',left:rect.left,right:rect.right,width:rect.width}}).filter(item=>item.right>innerWidth+2||item.left< -2).sort((a,b)=>b.right-a.right).slice(0,8))
    assert.fail(path+' overflows at '+width+': '+size.scroll+' '+JSON.stringify(overflow))
   }
  }
 }
 await page.setViewportSize({width:1440,height:700})
 await page.goto(ui+'/automation',{waitUntil:'domcontentloaded'})
 const sidebarBefore=await page.locator('.sidebar').evaluate(element=>({position:getComputedStyle(element).position,top:element.getBoundingClientRect().top}))
 await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight))
 const sidebarAfter=await page.locator('.sidebar').evaluate(element=>element.getBoundingClientRect().top)
 assert.equal(sidebarBefore.position,'fixed');assert.equal(sidebarAfter,sidebarBefore.top)
 pass('桌面侧边导航固定且不随页面滚动')
 assert.deepEqual(pageErrors,[])
 pass('22组已登录页面与响应式检查')
 const other=await fetch(api+'/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'other@example.test',displayName:'隔离用户',password:'QaPass123!'})}).then(r=>r.json())
 const cross=await fetch(api+'/resumes/'+resume.id,{headers:{Authorization:'Bearer '+other.accessToken}})
 assert.equal(cross.status,404)
 pass('账号数据隔离')
 const backup=await request('/workspace/backup')
 const restore=await fetch(api+'/workspace/restore',{method:'POST',headers:{Authorization:'Bearer '+other.accessToken,'Content-Type':'application/json'},body:JSON.stringify({...backup,acknowledged:true})})
 assert.equal(restore.status,200,await restore.text())
 const recovered=await fetch(api+'/resumes',{headers:{Authorization:'Bearer '+other.accessToken}}).then(r=>r.json())
 assert.equal(recovered.length,(await request('/resumes')).length)
 const restoredAgain=await fetch(api+'/workspace/restore',{method:'POST',headers:{Authorization:'Bearer '+other.accessToken,'Content-Type':'application/json'},body:JSON.stringify({...backup,acknowledged:true})})
 assert.equal(restoredAgain.status,409)
 pass('业务备份恢复到空账号并拒绝覆盖')
 await request('/auth/logout','POST')
 const loggedOut=await fetch(api+'/resumes',{headers:{Authorization:'Bearer '+token}})
 assert.equal(loggedOut.status,401)
 pass('退出令牌失效')
}finally{
 await browser?.close()
 for(const {child} of children.reverse()){child.kill()}
 console.log(JSON.stringify(results,null,2))
}
